"""Generate contextual enrichment sections for a drafted article.

Appends four structured HTML sections after the main article body:
- Контекст        (Background)
- Хронология      (Timeline)
- Какво следва    (What Happens Next)
- Защо е важно    (Why It Matters)

Each section is generated by the LLM in Bulgarian, grounded in article facts
and optionally in related past events retrieved from the Event registry.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from nasvetlo.logging_utils import get_logger
from nasvetlo.llm import load_prompt, call_llm_json

log = get_logger("drafting.context_expander")


class ContextSectionsResult(BaseModel):
    background: str = ""
    timeline: list[dict] = Field(default_factory=list)
    what_next: str = ""
    why_matters: str = ""


def expand_context(
    article_text: str,
    event_context: dict,
) -> ContextSectionsResult:
    """Call LLM to generate four contextual sections for the article.

    Parameters
    ----------
    article_text:
        The final revised article text in Bulgarian (markdown).
    event_context:
        Dict from ``build_event_context`` with keys:
        ``related_events``, ``existing_timeline``, ``existing_background``.

    Returns
    -------
    ContextSectionsResult — all four fields populated, or empty strings/lists
    on failure (so the article is never blocked by context expansion errors).
    """
    system_prompt = load_prompt("context_expander.txt")

    related = event_context.get("related_events", [])
    if related:
        lines = [
            f"- [{r.get('date', '')}] {r.get('title', '')} — {r.get('summary', '')}"
            for r in related
        ]
        related_block = "Related past events:\n" + "\n".join(lines)
    else:
        related_block = "No related past events available."

    user_prompt = f"{related_block}\n\n=== ARTICLE ===\n{article_text}"

    try:
        result_dict = call_llm_json(system=system_prompt, user=user_prompt)
        result = ContextSectionsResult(**result_dict)
        log.info(
            "Context expansion: background=%d chars, timeline=%d items, "
            "what_next=%d chars, why_matters=%d chars",
            len(result.background),
            len(result.timeline),
            len(result.what_next),
            len(result.why_matters),
        )
        return result
    except Exception as e:
        log.error("Context expansion failed: %s. Returning empty sections.", e)
        return ContextSectionsResult()


def build_context_html(sections: ContextSectionsResult) -> str:
    """Render ContextSectionsResult as HTML for appending to article body.

    Each non-empty section becomes a <section> block with a Bulgarian heading.
    Returns an empty string if all sections are empty (so body_html is unchanged).
    """
    parts: list[str] = []

    if sections.background:
        parts.append(
            '<section class="article-context context-background">'
            "<h3>Контекст</h3>"
            f"<p>{sections.background}</p>"
            "</section>"
        )

    if sections.timeline:
        items = "".join(
            f'<li><strong>{entry.get("date", "")}</strong>'
            f' — {entry.get("fact", "")}</li>'
            for entry in sections.timeline
            if entry.get("fact")
        )
        if items:
            parts.append(
                '<section class="article-context context-timeline">'
                "<h3>Хронология</h3>"
                f"<ul>{items}</ul>"
                "</section>"
            )

    if sections.what_next:
        parts.append(
            '<section class="article-context context-what-next">'
            "<h3>Какво следва</h3>"
            f"<p>{sections.what_next}</p>"
            "</section>"
        )

    if sections.why_matters:
        parts.append(
            '<section class="article-context context-why-matters">'
            "<h3>Защо е важно</h3>"
            f"<p>{sections.why_matters}</p>"
            "</section>"
        )

    if not parts:
        return ""

    return (
        '\n<div class="article-context-wrapper">\n'
        + "\n".join(parts)
        + "\n</div>"
    )
